### ISSUE TITLE
Mysql bug  

### ISSUE THREAD

**Issue by bbqc168** [KKiiya/BedWars-HotbarManager#2]
I build the plugins but the mysql isn't work and is only config
and the ERROR is: 
[19:48:13 INFO]: [HotbarManager] Enabling HotbarManager v1.2.1
[19:48:13 INFO]: [HotbarManager] Connecting to database...
[19:48:13 INFO]: [HotbarManager] Using MySQL as database provider!
[19:48:13 INFO]: [HotbarManager] Connecting to MySQL database...
[19:48:13 INFO]: [HotbarManager] Successfully connected!
[19:48:13 INFO]: [HotbarManager] Creating tables...
[19:48:13 ERROR]: Error occurred while enabling HotbarManager v1.2.1 (Is it up to date?)
java.lang.RuntimeException: Property 11451 does not exist on target class com.mysql.jdbc.jdbc2.optional.MysqlDataSource
        at com.zaxxer.hikari.util.PropertyElf.setProperty(PropertyElf.java:135) ~[com.zaxxer-HikariCP-3.4.5.jar:?]
        at com.zaxxer.hikari.util.PropertyElf.lambda$setTargetFromProperties$0(PropertyElf.java:59) ~[com.zaxxer-HikariCP-3.4.5.jar:?]
        at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603) ~[?:?]
        at java.util.Properties.forEach(Properties.java:1446) ~[?:?]
        at com.zaxxer.hikari.util.PropertyElf.setTargetFromProperties(PropertyElf.java:54) ~[com.zaxxer-HikariCP-3.4.5.jar:?]
        at com.zaxxer.hikari.pool.PoolBase.initializeDataSource(PoolBase.java:322) ~[com.zaxxer-HikariCP-3.4.5.jar:?]
        at com.zaxxer.hikari.pool.PoolBase.<init>(PoolBase.java:114) ~[com.zaxxer-HikariCP-3.4.5.jar:?]
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:108) ~[com.zaxxer-HikariCP-3.4.5.jar:?]
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112) ~[com.zaxxer-HikariCP-3.4.5.jar:?]
        at me.kiiya.hotbarmanager.database.providers.MySQL.createTables(MySQL.java:155) ~[?:?]
        at me.kiiya.hotbarmanager.database.providers.MySQL.<init>(MySQL.java:52) ~[?:?]
        at me.kiiya.hotbarmanager.support.bedwars1058.BedWars1058.connectDatabase(BedWars1058.java:47) ~[?:?]
        at me.kiiya.hotbarmanager.support.bedwars1058.BedWars1058.start(BedWars1058.java:37) ~[?:?]
        at me.kiiya.hotbarmanager.support.bedwars1058.BedWars1058.<init>(BedWars1058.java:26) ~[?:?]
        at me.kiiya.hotbarmanager.HotbarManager.loadSupport(HotbarManager.java:47) ~[?:?]
        at me.kiiya.hotbarmanager.HotbarManager.onEnable(HotbarManager.java:32) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched_1.8.8.jar:git-PaperSpigot-445]
        at java.lang.Thread.run(Thread.java:829) [?:?]
[19:48:13 INFO]: [HotbarManager] Disabling HotbarManager v1.2.1
so What should I do to fix the bug

**Comment by KKiiya** [comment]
Is this something that happened the first time you added the plugin? This is the first time i see something like this

**Comment by bbqc168** [comment]
no i added the plugin but i cant find mysql setting

**Comment by KKiiya** [comment]
Not enough explanations, old issue.
